SELECT vdd.VDD_ASSINATURA AS "VENDEDOR",
    ROUND(AVG(alc.ALC_SCORE), 2) AS "MEDIA_AVALIACAO",
    COUNT(*) AS "TOTAL_AVALIACOES"
FROM (
        SELECT ALC_ID AS ALC_ID,
            ALC_SCORE AS ALC_SCORE,
            ALC_CMP_ID AS ALC_CMP_ID
        FROM AVALIACAO_COMPRA
        UNION ALL
        SELECT HALC_ID AS ALC_ID,
            HALC_SCORE AS ALC_SCORE,
            HALC_CMP_ID AS ALC_CMP_ID
        FROM H_AVALIACAO_COMPRA
    ) alc
    JOIN (
        SELECT CMP_ID AS CMP_ID,
            CMP_VDD_ID AS CMP_VDD_ID
        FROM COMPRA
        UNION ALL
        SELECT HCMP_ID AS CMP_ID,
            HCMP_VDD_ID AS CMP_VDD_ID
        FROM H_COMPRA
    ) cmp ON cmp.CMP_ID = alc.ALC_CMP_ID
    JOIN (
        SELECT VDD_ID AS VDD_ID,
            VDD_ASSINATURA AS VDD_ASSINATURA
        FROM VENDEDOR
        UNION ALL
        SELECT HVDD_ID AS VDD_ID,
            HVDD_ASSINATURA AS VDD_ASSINATURA
        FROM H_VENDEDOR
    ) vdd ON vdd.VDD_ID = cmp.CMP_VDD_ID
GROUP BY vdd.VDD_ASSINATURA
ORDER BY "MEDIA_AVALIACAO" DESC
FETCH FIRST 10 ROWS ONLY;