SELECT cli.CLI_ID, cli.CLI_ASSINATURA,
    COUNT(DISTINCT TO_CHAR(cmp.CMP_DATA_COMPRA, 'YYYY-MM')) + COUNT(
        DISTINCT TO_CHAR(hcmp.HCMP_DATA_COMPRA, 'YYYY-MM')
    ) AS MESES_ATIVOS_TOTAL
FROM CLIENTE cli
    LEFT JOIN COMPRA cmp ON cli.CLI_ID = cmp.CMP_CLI_ID
    LEFT JOIN H_COMPRA hcmp ON cli.CLI_ID = hcmp.HCMP_CLI_ID
GROUP BY cli.CLI_ID, cli.CLI_ASSINATURA
ORDER BY MESES_ATIVOS_TOTAL DESC;