SELECT e.ETD_NOME AS ESTADO,
    COUNT(DISTINCT cmp.CMP_ID) AS TOTAL_COMPRAS,
    SUM(itc.ITC_PRECO * itc.ITC_QUANTIDADE) AS VALOR_TOTAL,
    ROUND(AVG(itc.ITC_PRECO * itc.ITC_QUANTIDADE), 2) AS TICKET_MEDIO
FROM COMPRA cmp
    JOIN CLIENTE cli ON cmp.CMP_CLI_ID = cli.CLI_ID
    JOIN CEP cep ON cli.CLI_CEP_ID = cep.CEP_ID
    JOIN CIDADE cid ON cep.CEP_CDD_ID = cid.CDD_ID
    JOIN ESTADO e ON cid.CDD_ETD_ID = e.ETD_ID
    JOIN ITEMS_COMPRA itc ON cmp.CMP_ID = itc.ITC_CMP_ID
GROUP BY e.ETD_NOME
ORDER BY VALOR_TOTAL DESC
FETCH FIRST 1 ROWS ONLY;