----------------------------------------------
-- COMENTARIOS
----------------------------------------------
-- COMENTARIOS - CIDADE
COMMENT ON TABLE CIDADE IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR CIDADES';
COMMENT ON COLUMN CIDADE.CDD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO PARA CIDADE';
COMMENT ON COLUMN CIDADE.CDD_NOME IS 'NOME DA CIDADE';
-- COMENTARIOS - ESTADO
COMMENT ON TABLE ESTADO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS ESTADOS';
COMMENT ON COLUMN ESTADO.ETD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO ESTADO';
COMMENT ON COLUMN ESTADO.ETD_NOME IS 'NOME DO ESTADO';