----------------------------------------------
-- COMENTARIOS
----------------------------------------------
-- COMENTARIOS - AVALIACAO COMPRA
COMMENT ON TABLE AVALIACAO_COMPRA IS 'RELAÇÃO RESPONSÁVEL PELA PERSISTÊNCIA DE AVALIAÇÕES DE COMPRAS';
COMMENT ON COLUMN AVALIACAO_COMPRA.ALC_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA AVALIAÇÃO';
COMMENT ON COLUMN AVALIACAO_COMPRA.ALC_SCORE IS 'SCORE DADO A COMPRA';
COMMENT ON COLUMN AVALIACAO_COMPRA.ALC_TITULO IS 'TÍTULO DA AVALIAÇÃO';
COMMENT ON COLUMN AVALIACAO_COMPRA.ALC_MENSAGEM IS 'MENSAGEM DA AVALIAÇÃO';
COMMENT ON COLUMN AVALIACAO_COMPRA.ALC_DATA_HORA_CRIACAO IS 'DATA DA INSCRIÇÃO DA AVALIAÇÃO';
COMMENT ON COLUMN AVALIACAO_COMPRA.ALC_CMP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE COMPRA AGREGADA';
-- COMENTARIOS - CATEGORIA PRODUTO
COMMENT ON TABLE CATEGORIA_PRODUTO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR AS CATEGORIAS DE UM PRODUTO';
COMMENT ON COLUMN CATEGORIA_PRODUTO.CTP_ID IS 'CÓDIGO IDENTIFICADOR DA CATEGORIA';
COMMENT ON COLUMN CATEGORIA_PRODUTO.CTP_NOME IS 'NOME DA CATEGORIA DO PRODUTO';
COMMENT ON COLUMN CATEGORIA_PRODUTO.CTP_NOME_INGLES IS 'NOME TRADUZIDO EM INGLÊS DA CATEGORIA';
-- COMENTARIOS - CEP
COMMENT ON TABLE CEP IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS CEPS';
COMMENT ON COLUMN CEP.CEP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO CEP';
COMMENT ON COLUMN CEP.CEP_LATITUDE IS 'LATITUDE DO CEP';
COMMENT ON COLUMN CEP.CEP_LONGITUDE IS 'LONGITUDE DO CEP';
COMMENT ON COLUMN CEP.CEP_CDD_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE CIDADE AGREGADA';
-- COMENTARIOS - CIDADE
COMMENT ON TABLE CIDADE IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR CIDADES';
COMMENT ON COLUMN CIDADE.CDD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO PARA CIDADE';
COMMENT ON COLUMN CIDADE.CDD_NOME IS 'NOME DA CIDADE';
COMMENT ON COLUMN CIDADE.CDD_ETD_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE ESTADO AGREGADO';
-- COMENTARIOS - CLIENTE
COMMENT ON TABLE CLIENTE IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS CLIENTES';
COMMENT ON COLUMN CLIENTE.CLI_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO CLIENTE';
COMMENT ON COLUMN CLIENTE.CLI_ASSINATURA IS 'ASSINATURA DO CLIENTE';
COMMENT ON COLUMN CLIENTE.CLI_CEP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE CEP AGREGADO';
-- COMENTARIOS - COMPRA
COMMENT ON TABLE COMPRA IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR AS COMPRAS EFETIVADAS';
COMMENT ON COLUMN COMPRA.CMP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA COMPRA';
COMMENT ON COLUMN COMPRA.CMP_ASSINATURA IS 'ASSINATURA DE EFETIVAÇÃO DA COMPRA';
COMMENT ON COLUMN COMPRA.CMP_DATA_COMPRA IS 'DATA  DE EFETIVAÇÃO DA COMPRA';
COMMENT ON COLUMN COMPRA.CMP_ENTREGA__PREVISTA IS 'DATA PREVISTA DE ENTREGA';
COMMENT ON COLUMN COMPRA.CMP_VDD_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE VENDEDOR AGREGADO';
COMMENT ON COLUMN COMPRA.CMP_CLI_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE CLIENTE AGREGADO';
-- COMENTARIOS - ESTADO
COMMENT ON TABLE ESTADO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS ESTADOS';
COMMENT ON COLUMN ESTADO.ETD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO ESTADO';
COMMENT ON COLUMN ESTADO.ETD_NOME IS 'NOME DO ESTADO';
-- COMENTARIOS - HISTORICO SITUACAO COMPRA
COMMENT ON TABLE HISTORICO_SITUACAO_COMPRA IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTÓRICO DE SITUAÇÕES DE UMA COMPRA';
COMMENT ON COLUMN HISTORICO_SITUACAO_COMPRA.HSC_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO PARA O HISTÓRICO DE SITUAÇÃO';
COMMENT ON COLUMN HISTORICO_SITUACAO_COMPRA.HSC_DATA_ATUALIZACAO IS 'DATA E HORA DA ÚLTIMA ATUALIZAÇÃO';
COMMENT ON COLUMN HISTORICO_SITUACAO_COMPRA.HSC_STC_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE HISTÓRICO DE COMPRA AGREGADA';
COMMENT ON COLUMN HISTORICO_SITUACAO_COMPRA.HSC_CMP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE COMPRA AGREGADA';
-- COMENTARIOS - ITEMS COMPRA
COMMENT ON TABLE ITEMS_COMPRA IS 'RELACIONAMENTO RESPONSÁVEL PELA INTERAÇÃO ENTRE COMPRAS E PRODUTOS PRESENTES NO ATO DA COMPRA';
COMMENT ON COLUMN ITEMS_COMPRA.ITC_PRD_ID IS 'IDENTIFICADOR ESTRANGEIRO REFERENCIAL DO PRODUTO';
COMMENT ON COLUMN ITEMS_COMPRA.ITC_CMP_ID IS 'IDENTIFICADOR ESTRANGEIRO REFERENCIAL DA COMPRA';
COMMENT ON COLUMN ITEMS_COMPRA.ITC_QUANTIDADE IS 'QUANTIDADE DE PRODUTOS COMPRADA';
COMMENT ON COLUMN ITEMS_COMPRA.ITC_ID IS 'IDENTIFICADOR INDEXAÇÃO ÚNICO DO ITEM DA COMPRA';
-- COMENTARIOS - PAGAMENTO
COMMENT ON TABLE PAGAMENTO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS PAGAMENTOS ASSOCIADOS A UMA COMPRA';
COMMENT ON COLUMN PAGAMENTO.PGM_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO PAGAMENTO';
COMMENT ON COLUMN PAGAMENTO.PGM_PARCELAS IS 'QUANTIDADE DE PARCELAS ASSOCIADAS AO PRODUTO';
COMMENT ON COLUMN PAGAMENTO.PGM_CMP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE COMPRA AGREGADA';
-- COMENTARIOS - PRODUTO
COMMENT ON TABLE PRODUTO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS PRODUTOS';
COMMENT ON COLUMN PRODUTO.PRD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO PRODUTO';
COMMENT ON COLUMN PRODUTO.PRD_CODIGO IS 'CÓDIGO DO PRODUTO';
COMMENT ON COLUMN PRODUTO.PRD_LARGURA IS 'LARGURA DO PRODUTO';
COMMENT ON COLUMN PRODUTO.PRD_PROFUNDIDADE IS 'PROFUNDIDADE DO PRODUTO';
COMMENT ON COLUMN PRODUTO.PRD_PRECO IS 'PREÇO ASSOCIADO A UM PRODUTO';
-- COMENTARIOS - SITUACAO COMPRA
COMMENT ON TABLE SITUACAO_COMPRA IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS TIPOS DE SITUAÇÃO DE COMPRA';
COMMENT ON COLUMN SITUACAO_COMPRA.STC_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA SITUAÇÃO DE COMPRA';
COMMENT ON COLUMN SITUACAO_COMPRA.STC_STATUS IS 'STATUS DA SITUAÇÃO DE COMPRA';
-- COMENTARIOS - TIPO PAGAMENTO
COMMENT ON TABLE TIPO_PAGAMENTO IS 'RELAÇÃO RESPONSÁVEL POR DEFINIR OS TIPOS DE PAGAMENTO DE UMA TRANSAÇÃO DE COMPRA';
COMMENT ON COLUMN TIPO_PAGAMENTO.TPG_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO TIPO DE PAGAMENTO';
COMMENT ON COLUMN TIPO_PAGAMENTO.TPG_CATEGORIA IS 'CATEGORIA DO TIPO DE PAGAMENTO';
-- COMENTARIOS - TRANSACOES PAGAMENTO
COMMENT ON TABLE TRANSACOES_PAGAMENTO IS 'RELAÇÃO  RESPONSÁVEL POR PERSISTIR AS TRANSAÇÕES ASSOCIADAS A UM PAGAMENTO';
COMMENT ON COLUMN TRANSACOES_PAGAMENTO.TNP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA TRANSAÇÃO';
COMMENT ON COLUMN TRANSACOES_PAGAMENTO.TNP_VALOR_PAGO IS 'VALOR PAGO NA TRANSAÇÃO';
COMMENT ON COLUMN TRANSACOES_PAGAMENTO.TNP_PGM_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO REFERENCIAL AO PAGAMENTO';
COMMENT ON COLUMN TRANSACOES_PAGAMENTO.TNP_TPG_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO REFERENCIAL AO TIPO DE PAGAMENTO';
-- COMENTARIOS - VENDEDOR
COMMENT ON TABLE VENDEDOR IS 'RELAÇÃO RESPONSÁVEL PELAS INFORMAÇÕES DO VENDEDOR';
COMMENT ON COLUMN VENDEDOR.VDD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO VENDEDOR';
COMMENT ON COLUMN VENDEDOR.VDD_ASSINATURA IS 'ASSINATURA DO VENDEDOR';
COMMENT ON COLUMN VENDEDOR.VDD_CEP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DO CEP AGREGADO';