----------------------------------------------
-- COMENTARIOS
----------------------------------------------
-- COMENTARIOS - CEP
COMMENT ON TABLE CEP IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS CEPS';
COMMENT ON COLUMN CEP.CEP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO CEP';
COMMENT ON COLUMN CEP.CEP_LATITUDE IS 'LATITUDE DO CEP';
COMMENT ON COLUMN CEP.CEP_LONGITUDE IS 'LONGITUDE DO CEP';
COMMENT ON COLUMN CEP.CEP_CDD_ID IS 'CÓDIGO DE IDENTIFICAÇÃO DA CIDADE DO CEP';
-- COMENTARIOS - CIDADE
COMMENT ON TABLE CIDADE IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR CIDADES';
COMMENT ON COLUMN CIDADE.CDD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO PARA CIDADE';
COMMENT ON COLUMN CIDADE.CDD_NOME IS 'NOME DA CIDADE';
COMMENT ON COLUMN CIDADE.CDD_ETD_ID IS 'CÓDIGO DE IDENTIFICAÇÃO DO ESTADO DA CIDADE';
-- COMENTARIOS - ESTADO
COMMENT ON TABLE ESTADO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS ESTADOS';
COMMENT ON COLUMN ESTADO.ETD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO ESTADO';
COMMENT ON COLUMN ESTADO.ETD_NOME IS 'NOME DO ESTADO';