----------------------------------------------
-- RESTRICOES RELACOES
----------------------------------------------
-- RESTRICOES - AVALIACAO_COMPRA
---- NOT NULL
ALTER TABLE AVALIACAO_COMPRA
MODIFY (
        "ALC_ID" CONSTRAINT "CK_ALC_NN_01" NOT NULL ENABLE
    );
ALTER TABLE AVALIACAO_COMPRA
MODIFY (
        "ALC_SCORE" CONSTRAINT "CK_ALC_NN_02" NOT NULL ENABLE
    );
ALTER TABLE AVALIACAO_COMPRA
MODIFY (
        "ALC_TITULO" CONSTRAINT "CK_ALC_NN_03" NOT NULL ENABLE
    );
ALTER TABLE AVALIACAO_COMPRA
MODIFY (
        "ALC_MENSAGEM" CONSTRAINT "CK_ALC_NN_04" NOT NULL ENABLE
    );
ALTER TABLE AVALIACAO_COMPRA
MODIFY (
        "ALC_DATA_HORA_CRIACAO" CONSTRAINT "CK_ALC_NN_05" NOT NULL ENABLE
    );
ALTER TABLE AVALIACAO_COMPRA
MODIFY (
        "ALC_CMP_ID" CONSTRAINT "CK_ALC_NN_06" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE AVALIACAO_COMPRA
ADD CONSTRAINT "PK_ALC" PRIMARY KEY ("ALC_ID");
-- RESTRICOES - CATEGORIA_PRODUTO
---- NOT NULL
ALTER TABLE CATEGORIA_PRODUTO
MODIFY (
        "CTP_ID" CONSTRAINT "CK_CTP_NN_01" NOT NULL ENABLE
    );
ALTER TABLE CATEGORIA_PRODUTO
MODIFY (
        "CTP_NOME" CONSTRAINT "CK_CTP_NN_02" NOT NULL ENABLE
    );
ALTER TABLE CATEGORIA_PRODUTO
MODIFY (
        "CTP_NOME_INGLES" CONSTRAINT "CK_CTP_NN_03" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE CATEGORIA_PRODUTO
ADD CONSTRAINT "PK_CTP" PRIMARY KEY ("CTP_ID");
-- RESTRICOES - CEP
---- NOT NULL
ALTER TABLE CEP
MODIFY (
        "CEP_ID" CONSTRAINT "CK_CEP_NN_01" NOT NULL ENABLE
    );
ALTER TABLE CEP
MODIFY (
        "CEP_LATITUDE" CONSTRAINT "CK_CEP_NN_02" NOT NULL ENABLE
    );
ALTER TABLE CEP
MODIFY (
        "CEP_LONGITUDE" CONSTRAINT "CK_CEP_NN_03" NOT NULL ENABLE
    );
ALTER TABLE CEP
MODIFY (
        "CEP_CDD_ID" CONSTRAINT "CK_CEP_NN_04" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE CEP
ADD CONSTRAINT "PK_CEP" PRIMARY KEY ("CEP_ID");
-- RESTRICOES - CIDADE
---- NOT NULL
ALTER TABLE CIDADE
MODIFY (
        "CDD_ID" CONSTRAINT "CK_CDD_NN_01" NOT NULL ENABLE
    );
ALTER TABLE CIDADE
MODIFY (
        "CDD_NOME" CONSTRAINT "CK_CDD_NN_02" NOT NULL ENABLE
    );
ALTER TABLE CIDADE
MODIFY (
        "CDD_ETD_ID" CONSTRAINT "CK_CDD_NN_03" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE CIDADE
ADD CONSTRAINT "PK_CDD" PRIMARY KEY ("CDD_ID");
-- RESTRICOES - CLIENTE
---- NOT NULL
ALTER TABLE CLIENTE
MODIFY (
        "CLI_ID" CONSTRAINT "CK_CLI_NN_01" NOT NULL ENABLE
    );
ALTER TABLE CLIENTE
MODIFY (
        "CLI_ASSINATURA" CONSTRAINT "CK_CLI_NN_02" NOT NULL ENABLE
    );
ALTER TABLE CLIENTE
MODIFY (
        "CLI_CEP_ID" CONSTRAINT "CK_CLI_NN_03" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE CLIENTE
ADD CONSTRAINT "PK_CLI" PRIMARY KEY ("CLI_ID");
-- RESTRICOES - COMPRA
---- NOT NULL
ALTER TABLE COMPRA
MODIFY (
        "CMP_ID" CONSTRAINT "CK_CMP_NN_01" NOT NULL ENABLE
    );
ALTER TABLE COMPRA
MODIFY (
        "CMP_ASSINATURA" CONSTRAINT "CK_CMP_NN_02" NOT NULL ENABLE
    );
ALTER TABLE COMPRA
MODIFY (
        "CMP_DATA_COMPRA" CONSTRAINT "CK_CMP_NN_03" NOT NULL ENABLE
    );
ALTER TABLE COMPRA
MODIFY (
        "CMP_ENTREGA__PREVISTA" CONSTRAINT "CK_CMP_NN_04" NOT NULL ENABLE
    );
ALTER TABLE COMPRA
MODIFY (
        "CMP_VDD_ID" CONSTRAINT "CK_CMP_NN_05" NOT NULL ENABLE
    );
ALTER TABLE COMPRA
MODIFY (
        "CMP_CLI_ID" CONSTRAINT "CK_CMP_NN_06" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE COMPRA
ADD CONSTRAINT "PK_CMP" PRIMARY KEY ("CMP_ID");
-- RESTRICOES - ESTADO
---- NOT NULL
ALTER TABLE ESTADO
MODIFY (
        "ETD_ID" CONSTRAINT "CK_ETD_NN_01" NOT NULL ENABLE
    );
ALTER TABLE ESTADO
MODIFY (
        "ETD_NOME" CONSTRAINT "CK_ETD_NN_02" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE ESTADO
ADD CONSTRAINT "PK_ETD" PRIMARY KEY ("ETD_ID");
-- RESTRICOES - HISTORICO_SITUACAO_COMPRA
---- NOT NULL
ALTER TABLE HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HSC_ID" CONSTRAINT "CK_HSC_NN_01" NOT NULL ENABLE
    );
ALTER TABLE HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HSC_DATA_ATUALIZACAO" CONSTRAINT "CK_HSC_NN_02" NOT NULL ENABLE
    );
ALTER TABLE HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HSC_STC_ID" CONSTRAINT "CK_HSC_NN_03" NOT NULL ENABLE
    );
ALTER TABLE HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HSC_CMP_ID" CONSTRAINT "CK_HSC_NN_04" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE HISTORICO_SITUACAO_COMPRA
ADD CONSTRAINT "PK_HSC" PRIMARY KEY ("HSC_ID");
-- RESTRICOES - ITEMS_COMPRA
---- NOT NULL
ALTER TABLE ITEMS_COMPRA
MODIFY (
        "ITC_ID" CONSTRAINT "CK_ITC_NN_01" NOT NULL ENABLE
    );
ALTER TABLE ITEMS_COMPRA
MODIFY (
        "ITC_PRD_ID" CONSTRAINT "CK_ITC_NN_02" NOT NULL ENABLE
    );
ALTER TABLE ITEMS_COMPRA
MODIFY (
        "ITC_CMP_ID" CONSTRAINT "CK_ITC_NN_03" NOT NULL ENABLE
    );
ALTER TABLE ITEMS_COMPRA
MODIFY (
        "ITC_QUANTIDADE" CONSTRAINT "CK_ITC_NN_04" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE ITEMS_COMPRA
ADD CONSTRAINT "PK_ITC" PRIMARY KEY ("ITC_ID");
-- RESTRICOES - PAGAMENTO
---- NOT NULL
ALTER TABLE PAGAMENTO
MODIFY (
        "PGM_ID" CONSTRAINT "CK_PGM_NN_01" NOT NULL ENABLE
    );
ALTER TABLE PAGAMENTO
MODIFY (
        "PGM_PARCELAS" CONSTRAINT "CK_PGM_NN_02" NOT NULL ENABLE
    );
ALTER TABLE PAGAMENTO
MODIFY (
        "PGM_CMP_ID" CONSTRAINT "CK_PGM_NN_03" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE PAGAMENTO
ADD CONSTRAINT "PK_PGM" PRIMARY KEY ("PGM_ID");
-- RESTRICOES - PRODUTO
---- NOT NULL
ALTER TABLE PRODUTO
MODIFY (
        "PRD_ID" CONSTRAINT "CK_PRD_NN_01" NOT NULL ENABLE
    );
ALTER TABLE PRODUTO
MODIFY (
        "PRD_CODIGO" CONSTRAINT "CK_PRD_NN_02" NOT NULL ENABLE
    );
ALTER TABLE PRODUTO
MODIFY (
        "PRD_LARGURA" CONSTRAINT "CK_PRD_NN_03" NOT NULL ENABLE
    );
ALTER TABLE PRODUTO
MODIFY (
        "PRD_PROFUNDIDADE" CONSTRAINT "CK_PRD_NN_04" NOT NULL ENABLE
    );
ALTER TABLE PRODUTO
MODIFY (
        "PRD_PRECO" CONSTRAINT "CK_PRD_NN_05" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE PRODUTO
ADD CONSTRAINT "PK_PRD" PRIMARY KEY ("PRD_ID");
-- RESTRICOES - PRODUTO_CATEGORIA
---- NOT NULL
ALTER TABLE PRODUTO_CATEGORIA
MODIFY (
        "PRC_PRD_ID" CONSTRAINT "CK_PRC_NN_01" NOT NULL ENABLE
    );
ALTER TABLE PRODUTO_CATEGORIA
MODIFY (
        "PRC_CTP_ID" CONSTRAINT "CK_PRC_NN_02" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE PRODUTO_CATEGORIA
ADD CONSTRAINT "PK_PRC" PRIMARY KEY ("PRC_PRD_ID", "PRC_CTP_ID");
-- RESTRICOES - SITUACAO_COMPRA
---- NOT NULL
ALTER TABLE SITUACAO_COMPRA
MODIFY (
        "STC_ID" CONSTRAINT "CK_STC_NN_01" NOT NULL ENABLE
    );
ALTER TABLE SITUACAO_COMPRA
MODIFY (
        "STC_STATUS" CONSTRAINT "CK_STC_NN_02" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE SITUACAO_COMPRA
ADD CONSTRAINT "PK_STC" PRIMARY KEY ("STC_ID");
-- RESTRICOES - TRANSACOES_PAGAMENTO
---- NOT NULL
ALTER TABLE TRANSACOES_PAGAMENTO
MODIFY (
        "TNP_ID" CONSTRAINT "CK_TNP_NN_01" NOT NULL ENABLE
    );
ALTER TABLE TRANSACOES_PAGAMENTO
MODIFY (
        "TNP_VALOR_PAGO" CONSTRAINT "CK_TNP_NN_02" NOT NULL ENABLE
    );
ALTER TABLE TRANSACOES_PAGAMENTO
MODIFY (
        "TNP_PGM_ID" CONSTRAINT "CK_TNP_NN_03" NOT NULL ENABLE
    );
ALTER TABLE TRANSACOES_PAGAMENTO
MODIFY (
        "TNP_TPG_ID" CONSTRAINT "CK_TNP_NN_04" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE TRANSACOES_PAGAMENTO
ADD CONSTRAINT "PK_TNP" PRIMARY KEY ("TNP_ID");
-- RESTRICOES - TIPO_PAGAMENTO
---- NOT NULL
ALTER TABLE TIPO_PAGAMENTO
MODIFY (
        "TPG_ID" CONSTRAINT "CK_TPG_NN_01" NOT NULL ENABLE
    );
ALTER TABLE TIPO_PAGAMENTO
MODIFY (
        "TPG_CATEGORIA" CONSTRAINT "CK_TPG_NN_02" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE TIPO_PAGAMENTO
ADD CONSTRAINT "PK_TPG" PRIMARY KEY ("TPG_ID");
-- RESTRICOES - VENDEDOR
---- NOT NULL
ALTER TABLE VENDEDOR
MODIFY (
        "VDD_ID" CONSTRAINT "CK_VDD_NN_01" NOT NULL ENABLE
    );
ALTER TABLE VENDEDOR
MODIFY (
        "VDD_ASSINATURA" CONSTRAINT "CK_VDD_NN_02" NOT NULL ENABLE
    );
ALTER TABLE VENDEDOR
MODIFY (
        "VDD_CEP_ID" CONSTRAINT "CK_VDD_NN_03" NOT NULL ENABLE
    );
---- CHAVE PRIMARIA
ALTER TABLE VENDEDOR
ADD CONSTRAINT "PK_VDD" PRIMARY KEY ("VDD_ID");
----------------------------------------------
-- RESTRICOES DE CHAVES ESTRANGEIRAS
----------------------------------------------
ALTER TABLE AVALIACAO_COMPRA
ADD CONSTRAINT "FK_ALC_CMP" FOREIGN KEY ("ALC_CMP_ID") REFERENCES COMPRA ("CMP_ID") ENABLE;
ALTER TABLE CEP
ADD CONSTRAINT "FK_CEP_CDD" FOREIGN KEY ("CEP_CDD_ID") REFERENCES CIDADE ("CDD_ID") ENABLE;
ALTER TABLE CLIENTE
ADD CONSTRAINT "FK_CLI_CEP" FOREIGN KEY ("CLI_CEP_ID") REFERENCES CEP ("CEP_ID") ENABLE;
ALTER TABLE COMPRA
ADD CONSTRAINT "FK_CMP_CLI" FOREIGN KEY ("CMP_CLI_ID") REFERENCES CLIENTE ("CLI_ID") ENABLE;
ALTER TABLE COMPRA
ADD CONSTRAINT "FK_CMP_VDD" FOREIGN KEY ("CMP_VDD_ID") REFERENCES VENDEDOR ("VDD_ID") ENABLE;
ALTER TABLE HISTORICO_SITUACAO_COMPRA
ADD CONSTRAINT "FK_HSC_CMP" FOREIGN KEY ("HSC_CMP_ID") REFERENCES COMPRA ("CMP_ID") ENABLE;
ALTER TABLE HISTORICO_SITUACAO_COMPRA
ADD CONSTRAINT "FK_HSC_STC" FOREIGN KEY ("HSC_STC_ID") REFERENCES SITUACAO_COMPRA ("STC_ID") ENABLE;
ALTER TABLE ITEMS_COMPRA
ADD CONSTRAINT "FK_ITC_CMP" FOREIGN KEY ("ITC_CMP_ID") REFERENCES COMPRA ("CMP_ID") ENABLE;
ALTER TABLE ITEMS_COMPRA
ADD CONSTRAINT "FK_ITC_PRD" FOREIGN KEY ("ITC_PRD_ID") REFERENCES PRODUTO ("PRD_ID") ENABLE;
ALTER TABLE PAGAMENTO
ADD CONSTRAINT "FK_PGM_CMP" FOREIGN KEY ("PGM_CMP_ID") REFERENCES COMPRA ("CMP_ID") ENABLE;
ALTER TABLE PRODUTO_CATEGORIA
ADD CONSTRAINT "FK_PRC_CTP" FOREIGN KEY ("PRC_CTP_ID") REFERENCES CATEGORIA_PRODUTO ("CTP_ID") ENABLE;
ALTER TABLE PRODUTO_CATEGORIA
ADD CONSTRAINT "FK_PRC_PRD" FOREIGN KEY ("PRC_PRD_ID") REFERENCES PRODUTO ("PRD_ID") ENABLE;
ALTER TABLE TRANSACOES_PAGAMENTO
ADD CONSTRAINT "FK_TNP_PGM" FOREIGN KEY ("TNP_PGM_ID") REFERENCES PAGAMENTO ("PGM_ID") ENABLE;
ALTER TABLE TRANSACOES_PAGAMENTO
ADD CONSTRAINT "FK_TNP_TPG" FOREIGN KEY ("TNP_TPG_ID") REFERENCES TIPO_PAGAMENTO ("TPG_ID") ENABLE;
ALTER TABLE VENDEDOR
ADD CONSTRAINT "FK_VDD_CEP" FOREIGN KEY ("VDD_CEP_ID") REFERENCES CEP ("CEP_ID") ENABLE;