---------------------------------------
-- TRIGGERS DE HISTORIAMENTO
-- Define as rotinas executadas para historiamento das entidades
---------------------------------------

-- TRIGGER - H_AVALIACAO_COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HALC
BEFORE UPDATE OR DELETE ON AVALIACAO_COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO H_AVALIACAO_COMPRA (
        HALC_ID,
        HALC_SCORE,
        HALC_TITULO,
        HALC_MENSAGEM,
        HALC_DATA_HORA_CRIACAO,
        HALC_CMP_ID,
        HALC_DATA_CRIACAO
    )
    VALUES (
        :OLD.ALC_ID,
        :OLD.ALC_SCORE,
        :OLD.ALC_TITULO,
        :OLD.ALC_MENSAGEM,
        :OLD.ALC_DATA_HORA_CRIACAO,
        :OLD.ALC_CMP_ID,
        SYSDATE
    );
END;
/

-- TRIGGER - H_CATEGORIA_PRODUTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HCTP
BEFORE UPDATE OR DELETE ON CATEGORIA_PRODUTO
FOR EACH ROW
BEGIN
    INSERT INTO H_CATEGORIA_PRODUTO (
        HCTP_ID,
        HCTP_NOME,
        HCTP_NOME_INGLES,
        HCTP_DATA_CRIACAO
    )
    VALUES (
        :OLD.CTP_ID,
        :OLD.CTP_NOME,
        :OLD.CTP_NOME_INGLES,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_CEP
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HCEP
BEFORE UPDATE OR DELETE ON CEP
FOR EACH ROW
BEGIN
    INSERT INTO H_CEP (
        HCEP_ID,
        HCEP_LATITUDE,
        HCEP_LONGITUDE,
        HCEP_CDD_ID,
        HCEP_DATA_CRIACAO
    )
    VALUES (
        :OLD.CEP_ID,
        :OLD.CEP_LATITUDE,
        :OLD.CEP_LONGITUDE,
        :OLD.CDD_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_CIDADE
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HCDD
BEFORE UPDATE OR DELETE ON CIDADE
FOR EACH ROW
BEGIN
    INSERT INTO H_CIDADE (
        HCDD_ID,
        HCDD_NOME,
        HCDD_ETD_ID,
        HCDD_DATA_CRIACAO
    )
    VALUES (
        :OLD.CDD_ID,
        :OLD.CDD_NOME,
        :OLD.CDD_ETD_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_CLIENTE
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HCLI
BEFORE UPDATE OR DELETE ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO H_CLIENTE (
        HCLI_ID,
        HCLI_ASSINATURA,
        HCLI_CEP_ID,
        HCLI_DATA_CRIACAO
    )
    VALUES (
        :OLD.CLI_ID,
        :OLD.CLI_ASSINATURA,
        :OLD.CEP_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HCMP
BEFORE UPDATE OR DELETE ON COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO H_COMPRA (
        HCMP_ID,
        HCMP_ASSINATURA,
        HCMP_DATA_COMPRA,
        HCMP_ENTREGA__PREVISTA,
        HCMP_VDD_ID,
        HCMP_CLI_ID,
        HCMP_DATA_CRIACAO
    )
    VALUES (
        :OLD.CMP_ID,
        :OLD.CMP_ASSINATURA,
        :OLD.CMP_DATA_COMPRA,
        :OLD.CMP_ENTREGA__PREVISTA,
        :OLD.CMP_VDD_ID,
        :OLD.CMP_CLI_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_ESTADO
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HETD
BEFORE UPDATE OR DELETE ON ESTADO
FOR EACH ROW
BEGIN
    INSERT INTO H_ESTADO (
        HETD_ID,
        HETD_NOME,
        HETD_DATA_CRIACAO
    )
    VALUES (
        :OLD.ETD_ID,
        :OLD.ETD_NOME,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_HISTORICO_SITUACAO_COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HHSC
BEFORE UPDATE OR DELETE ON HISTORICO_SITUACAO_COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO H_HISTORICO_SITUACAO_COMPRA (
        HHSC_ID,
        HHSC_DATA_ATUALIZACAO,
        HHSC_STC_ID,
        HHSC_CMP_ID,
        HHSC_DATA_CRIACAO
    )
    VALUES (
        :OLD.HSC_ID,
        :OLD.HSC_DATA_ATUALIZACAO,
        :OLD.HSC_STC_ID,
        :OLD.HSC_CMP_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_ITEMS_COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HITC
BEFORE UPDATE OR DELETE ON ITEMS_COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO H_ITEMS_COMPRA (
        HITC_PRD_ID,
        HITC_CMP_ID,
        HITC_QUANTIDADE,
        HITC_PRECO,
        HITC_ID,
        HITC_DATA_CRIACAO
    )
    VALUES (
        :OLD.ITC_PRD_ID,
        :OLD.ITC_CMP_ID,
        :OLD.ITC_QUANTIDADE,
        :OLD.ITC_PRECO,
        :OLD.ITC_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_PAGAMENTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HPGM
BEFORE UPDATE OR DELETE ON PAGAMENTO
FOR EACH ROW
BEGIN
    INSERT INTO H_PAGAMENTO (
        HPGM_ID,
        HPGM_PARCELAS,
        HPGM_CMP_ID,
        HPGM_DATA_CRIACAO
    )
    VALUES (
        :OLD.PGM_ID,
        :OLD.PGM_PARCELAS,
        :OLD.PGM_CMP_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_PRODUTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HPRD
BEFORE UPDATE OR DELETE ON PRODUTO
FOR EACH ROW
BEGIN
    INSERT INTO H_PRODUTO (
        HPRD_ID,
        HPRD_CODIGO,
        HPRD_LARGURA,
        HPRD_PROFUNDIDADE,
        HPRD_PRECO,
        HPRD_DATA_CRIACAO
    )
    VALUES (
        :OLD.PRD_ID,
        :OLD.PRD_CODIGO,
        :OLD.PRD_LARGURA,
        :OLD.PRD_PROFUNDIDADE,
        :OLD.PRD_PRECO,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_PRODUTO_CATEGORIA
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HPRC
BEFORE UPDATE OR DELETE ON PRODUTO_CATEGORIA
FOR EACH ROW
BEGIN
    INSERT INTO H_PRODUTO_CATEGORIA (
        HPRC_PRD_ID,
        HPRC_CTP_ID,
        HPRC_DATA_CRIACAO
    )
    VALUES (
        :OLD.PRC_PRD_ID,
        :OLD.PRC_CTP_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_SITUACAO_COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HSTC
BEFORE UPDATE OR DELETE ON SITUACAO_COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO H_SITUACAO_COMPRA (
        HSTC_ID,
        HSTC_STATUS,
        HSTC_DATA_CRIACAO
    )
    VALUES (
        :OLD.STC_ID,
        :OLD.STC_STATUS,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_TRANSACOES_PAGAMENTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HTNP
BEFORE UPDATE OR DELETE ON TRANSACOES_PAGAMENTO
FOR EACH ROW
BEGIN
    INSERT INTO H_TRANSACOES_PAGAMENTO (
        HTNP_ID,
        HTNP_VALOR_PAGO,
        HTNP_PGM_ID,
        HTNP_TPG_ID,
        HTNP_DATA_CRIACAO
    )
    VALUES (
        :OLD.TNP_ID,
        :OLD.TNP_VALOR_PAGO,
        :OLD.TNP_PGM_ID,
        :OLD.TNP_TPG_ID,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_TIPO_PAGAMENTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HTPG
BEFORE UPDATE OR DELETE ON TIPO_PAGAMENTO
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPO_PAGAMENTO (
        HTPG_ID,
        HTPG_CATEGORIA,
        HTPG_DATA_CRIACAO
    )
    VALUES (
        :OLD.TPG_ID,
        :OLD.TPG_CATEGORIA,
        SYSTIMESTAMP
    );
END;
/

-- TRIGGER - H_VENDEDOR
CREATE OR REPLACE NONEDITIONABLE TRIGGER TG_HVDD
BEFORE UPDATE OR DELETE ON VENDEDOR
FOR EACH ROW
BEGIN
    INSERT INTO H_VENDEDOR (
        HVDD_ID,
        HVDD_ASSINATURA,
        HVDD_CEP_ID,
        HVDD_DATA_CRIACAO
    )
    VALUES (
        :OLD.VDD_ID,
        :OLD.VDD_ASSINATURA,
        :OLD.CEP_ID,
        SYSTIMESTAMP
    );
END;
/
