---------------------------------------
-- RELAÇÕES DE HISTORIAMENTO
-- Define o historiamento das entidades principais do minimundo
---------------------------------------
-- HISTORIAMENTO - RELACAO AVALIACAO COMPRA
CREATE TABLE H_AVALIACAO_COMPRA (
    HALC_ID NUMBER (10),
    HALC_SCORE NUMBER (2, 2),
    HALC_TITULO VARCHAR2 (90 CHAR),
    HALC_MENSAGEM CLOB,
    HALC_DATA_HORA_CRIACAO DATE,
    HALC_CMP_ID NUMBER (10),
    HALC_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO CATEGORIA PRODUTO
CREATE TABLE H_CATEGORIA_PRODUTO (
    HCTP_ID NUMBER (4),
    HCTP_NOME VARCHAR2 (40 CHAR),
    HCTP_NOME_INGLES VARCHAR2 (40 CHAR),
    HCTP_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO CEP
CREATE TABLE H_CEP (
    HCEP_ID NUMBER (6),
    HCEP_LATITUDE NUMBER (9, 6),
    HCEP_LONGITUDE NUMBER (9, 6),
    HCEP_CDD_ID NUMBER (4),
    HCEP_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO CIDADE
CREATE TABLE H_CIDADE (
    HCDD_ID NUMBER (4),
    HCDD_NOME VARCHAR2 (40 CHAR),
    HCDD_ETD_ID NUMBER (2),
    HCDD_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO CLIENTE
CREATE TABLE H_CLIENTE (
    HCLI_ID NUMBER (8),
    HCLI_ASSINATURA VARCHAR2 (60 CHAR),
    HCLI_CEP_ID NUMBER (6),
    HCLI_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO COMPRA
CREATE TABLE H_COMPRA (
    HCMP_ID NUMBER (10),
    HCMP_ASSINATURA VARCHAR2 (60 CHAR),
    HCMP_DATA_COMPRA DATE,
    HCMP_ENTREGA__PREVISTA DATE,
    HCMP_VDD_ID NUMBER (8),
    HCMP_CLI_ID NUMBER (8),
    HCMP_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO ESTADO
CREATE TABLE H_ESTADO (
    HETD_ID NUMBER (2),
    HETD_NOME VARCHAR2 (25),
    HETD_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO HISTORICO SITUACAO COMPRA
CREATE TABLE H_HISTORICO_SITUACAO_COMPRA (
    HHSC_ID NUMBER (10),
    HHSC_DATA_ATUALIZACAO DATE,
    HHSC_STC_ID NUMBER (2),
    HHSC_CMP_ID NUMBER (10),
    HHSC_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO ITEMS COMPRA
CREATE TABLE H_ITEMS_COMPRA (
    HITC_PRD_ID NUMBER (6),
    HITC_CMP_ID NUMBER (10),
    HITC_QUANTIDADE NUMBER (6),
    HITC_ID NUMBER (10),
    HITC_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO PAGAMENTO
CREATE TABLE H_PAGAMENTO (
    HPGM_ID NUMBER (10),
    HPGM_PARCELAS NUMBER (3),
    HPGM_CMP_ID NUMBER (10),
    HPGM_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO PRODUTO
CREATE TABLE H_PRODUTO (
    HPRD_ID NUMBER (6),
    HPRD_CODIGO VARCHAR2 (100 CHAR),
    HPRD_LARGURA NUMBER (4),
    HPRD_PROFUNDIDADE NUMBER (5),
    HPRD_PRECO NUMBER (4, 2),
    HPRD_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO PRODUTO CATEGORIA
CREATE TABLE H_PRODUTO_CATEGORIA (
    HPRC_PRD_ID NUMBER (6),
    HPRC_CTP_ID NUMBER (4),
    HPRC_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO SITUACAO COMPRA
CREATE TABLE H_SITUACAO_COMPRA (
    HSTC_ID NUMBER (2),
    HSTC_STATUS VARCHAR2 (15),
    HSTC_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO TRANSACOES PAGAMENTO
CREATE TABLE H_TRANSACOES_PAGAMENTO (
    HTNP_ID NUMBER (10),
    HTNP_VALOR_PAGO NUMBER (6, 2),
    HTNP_PGM_ID NUMBER (10),
    HTNP_TPG_ID NUMBER (2),
    HTNP_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO TIPO PAGAMENTO
CREATE TABLE H_TIPO_PAGAMENTO (
    HTPG_ID NUMBER (2),
    HTPG_CATEGORIA VARCHAR2 (15 CHAR),
    HTPG_DATA_CRIACAO DATE
) LOGGING;
-- HISTORIAMENTO - RELACAO VENDEDOR
CREATE TABLE H_VENDEDOR (
    HVDD_ID NUMBER (8),
    HVDD_ASSINATURA VARCHAR2 (60 CHAR),
    HVDD_CEP_ID NUMBER (6),
    HVDD_DATA_CRIACAO DATE
) LOGGING;