----------------------------------------------
-- COMENTARIOS - RELAÇÕES HISTORIAMENTO
----------------------------------------------
-- COMENTARIOS - H_AVALIACAO COMPRA
COMMENT ON TABLE H_AVALIACAO_COMPRA IS 'RELAÇÃO RESPONSÁVEL PELA PERSISTÊNCIA DE AVALIAÇÕES DE COMPRAS';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA AVALIAÇÃO HISTORIADA';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_SCORE IS 'SCORE DADO A COMPRA HISTORIADA';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_TITULO IS 'TÍTULO DA AVALIAÇÃO HISTORIADA';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_MENSAGEM IS 'MENSAGEM DA AVALIAÇÃO HISTORIADA';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_DATA_HORA_CRIACAO IS 'DATA DA INSCRIÇÃO DA AVALIAÇÃO HISTORIADA';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_CMP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE COMPRA AGREGADA HISTORIADA';
COMMENT ON COLUMN H_AVALIACAO_COMPRA.HALC_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO DA AVALIAÇÃO DE COMPRA HISTORIADA';
-- COMENTARIOS - H_CATEGORIA_PRODUTO
COMMENT ON TABLE H_CATEGORIA_PRODUTO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DAS CATEGORIAS DE UM PRODUTO';
COMMENT ON COLUMN H_CATEGORIA_PRODUTO.HCTP_ID IS 'CÓDIGO IDENTIFICADOR DA CATEGORIA HISTORIADA';
COMMENT ON COLUMN H_CATEGORIA_PRODUTO.HCTP_NOME IS 'NOME DA CATEGORIA DO PRODUTO HISTORIADO';
COMMENT ON COLUMN H_CATEGORIA_PRODUTO.HCTP_NOME_INGLES IS 'NOME TRADUZIDO EM INGLÊS DA CATEGORIA HISTORIADA';
COMMENT ON COLUMN H_CATEGORIA_PRODUTO.HCTP_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DA CATEGORIA DE PRODUTO HISTORIADA';
-- COMENTARIOS - H_CEP
COMMENT ON TABLE H_CEP IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DOS CEPS';
COMMENT ON COLUMN H_CEP.HCEP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO CEP HISTORIADO';
COMMENT ON COLUMN H_CEP.HCEP_LATITUDE IS 'LATITUDE DO CEP HISTORIADO';
COMMENT ON COLUMN H_CEP.HCEP_LONGITUDE IS 'LONGITUDE DO CEP HISTORIADO';
COMMENT ON COLUMN H_CEP.HCEP_CDD_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE CIDADE AGREGADA AO CEP HISTORIADO';
COMMENT ON COLUMN H_CEP.HCEP_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO CEP HISTORIADO';
-- COMENTARIOS - H_CIDADE
COMMENT ON TABLE H_CIDADE IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DAS CIDADES';
COMMENT ON COLUMN H_CIDADE.HCDD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO PARA CIDADE HISTORIADA';
COMMENT ON COLUMN H_CIDADE.HCDD_NOME IS 'NOME DA CIDADE HISTORIADA';
COMMENT ON COLUMN H_CIDADE.HCDD_ETD_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE ESTADO AGREGADO A CIDADE HISTORIADA';
COMMENT ON COLUMN H_CIDADE.HCDD_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DA CIDADE HISTORIADA';
-- COMENTARIOS - H_CLIENTE
COMMENT ON TABLE H_CLIENTE IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DOS CLIENTES';
COMMENT ON COLUMN H_CLIENTE.HCLI_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO CLIENTE HISTORIADO';
COMMENT ON COLUMN H_CLIENTE.HCLI_ASSINATURA IS 'ASSINATURA DO CLIENTE HISTORIADO';
COMMENT ON COLUMN H_CLIENTE.HCLI_CEP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE CEP AGREGADO AO CLIENTE HISTORIADO';
COMMENT ON COLUMN H_CLIENTE.HCLI_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO CLIENTE HISTORIADO';
-- COMENTARIOS - H_COMPRA
COMMENT ON TABLE H_COMPRA IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DAS COMPRAS EFETIVADAS';
COMMENT ON COLUMN H_COMPRA.HCMP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA COMPRA HISTORIADA';
COMMENT ON COLUMN H_COMPRA.HCMP_ASSINATURA IS 'ASSINATURA DE EFETIVAÇÃO DA COMPRA HISTORIADA';
COMMENT ON COLUMN H_COMPRA.HCMP_DATA_COMPRA IS 'DATA  DE EFETIVAÇÃO DA COMPRA HISTORIADA';
COMMENT ON COLUMN H_COMPRA.HCMP_ENTREGA__PREVISTA IS 'DATA PREVISTA DE ENTREGA HISTORIADA';
COMMENT ON COLUMN H_COMPRA.HCMP_VDD_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE VENDEDOR AGREGADO A COMPRA HISTORIADA';
COMMENT ON COLUMN H_COMPRA.HCMP_CLI_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE CLIENTE AGREGADO A COMPRA HISTORIADA';
COMMENT ON COLUMN H_COMPRA.HCMP_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DA COMPRA HISTORIADA';
-- COMENTARIOS - H_ESTADO
COMMENT ON TABLE H_ESTADO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DOS ESTADOS';
COMMENT ON COLUMN H_ESTADO.HETD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO ESTADO HISTORIADO';
COMMENT ON COLUMN H_ESTADO.ETD_NOME IS 'NOME DO ESTADO HISTORIADO';
COMMENT ON COLUMN H_ESTADO.HTED_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO ESTADO HISTORIADO';
-- COMENTARIOS - H_HISTORICO_SITUACAO_COMPRA
COMMENT ON TABLE H_HISTORICO_SITUACAO_COMPRA IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTÓRICO DE SITUAÇÕES DE UMA COMPRA';
COMMENT ON COLUMN H_HISTORICO_SITUACAO_COMPRA.HSC_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO PARA O HISTÓRICO DE SITUAÇÃO';
COMMENT ON COLUMN H_HISTORICO_SITUACAO_COMPRA.HSC_DATA_ATUALIZACAO IS 'DATA E HORA DA ÚLTIMA ATUALIZAÇÃO';
COMMENT ON COLUMN H_HISTORICO_SITUACAO_COMPRA.HSC_STC_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE HISTÓRICO DE COMPRA AGREGADA';
COMMENT ON COLUMN H_HISTORICO_SITUACAO_COMPRA.HSC_CMP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE COMPRA AGREGADA';
COMMENT ON COLUMN H_HISTORICO_SITUACAO_COMPRA.HHSC_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO HISTÓRICO DE SITUAÇÃO DE COMPRA HISTORIADA';
-- COMENTARIOS - H_ITEMS_COMPRA
COMMENT ON TABLE H_ITEMS_COMPRA IS 'RELACIONAMENTO RESPONSÁVEL PELO HISTORIAMENTO DA INTERAÇÃO ENTRE COMPRAS E PRODUTOS PRESENTES NO ATO DA COMPRA';
COMMENT ON COLUMN H_ITEMS_COMPRA.HITC_PRD_ID IS 'IDENTIFICADOR ESTRANGEIRO REFERENCIAL DO PRODUTO EM HISTORIAMENTO';
COMMENT ON COLUMN H_ITEMS_COMPRA.HITC_CMP_ID IS 'IDENTIFICADOR ESTRANGEIRO REFERENCIAL DA COMPRA EM HISTORIAMENTO';
COMMENT ON COLUMN H_ITEMS_COMPRA.HITC_QUANTIDADE IS 'QUANTIDADE DE PRODUTOS COMPRADO EM HISTORIAMENTO';
COMMENT ON COLUMN H_ITEMS_COMPRA.HITC_ID IS 'IDENTIFICADOR INDEXAÇÃO ÚNICO DO ITEM DA COMPRA HISTORIADA';
COMMENT ON COLUMN H_ITEMS_COMPRA.HITC_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO ITEM DA COMPRA HISTORIADO';
-- COMENTARIOS - H_PAGAMENTO
COMMENT ON TABLE H_PAGAMENTO IS 'RELAÇÃO DE HISTORIAMENTO DOS PAGAMENTOS DE UMA COMPRA';
COMMENT ON COLUMN H_PAGAMENTO.HPGM_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO PAGAMENTO HISTORIADO';
COMMENT ON COLUMN H_PAGAMENTO.HPGM_PARCELAS IS 'QUANTIDADE DE PARCELAS ASSOCIADAS AO PRODUTO HISTORIADO';
COMMENT ON COLUMN H_PAGAMENTO.HPGM_CMP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DE COMPRA AGREGADA AO PAGAMENTO HISTORIADO';
COMMENT ON COLUMN H_PAGAMENTO.HPGM_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO PAGAMENTO HISTORIADO';
-- COMENTARIOS - H_PRODUTO
COMMENT ON TABLE H_PRODUTO IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DOS PRODUTOS';
COMMENT ON COLUMN H_PRODUTO.HPRD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO PRODUTO HISTORIADO';
COMMENT ON COLUMN H_PRODUTO.HPRD_CODIGO IS 'CÓDIGO DO PRODUTO HISTORIADO';
COMMENT ON COLUMN H_PRODUTO.HPRD_LARGURA IS 'LARGURA DO PRODUTO HISTORIADO';
COMMENT ON COLUMN H_PRODUTO.HPRD_PROFUNDIDADE IS 'PROFUNDIDADE DO PRODUTO HISTORIADO';
COMMENT ON COLUMN H_PRODUTO.HPRD_PRECO IS 'PREÇO ASSOCIADO A UM PRODUTO HISTORIADO';
COMMENT ON COLUMN H_PRODUTO.HPRD_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO PRODUTO HISTORIADO';
-- COMENTARIOS - H_PRODUTO_CATEGORIA
COMMENT ON TABLE H_PRODUTO_CATEGORIA IS 'RELACIONAMENTO RESPONSÁVEL PELO HISTORIAMENTO DA INTERAÇÃO ENTRE PRODUTOS E CATEGORIAS DE UM PRODUTO';
COMMENT ON COLUMN H_PRODUTO_CATEGORIA.HPRC_PRD_ID IS 'CHAVE ESTRANGEIRA REFERENCIAL AO PRODUTO EM HISTORIAMENTO';
COMMENT ON COLUMN H_PRODUTO_CATEGORIA.HPRC_CTP_ID IS 'CHAVE ESTRANGEIRA REFERENCIAL DA CATEGORIA DO PRODUTO EM HISTORIAMENTO';
COMMENT ON COLUMN H_PRODUTO_CATEGORIA.HPRC_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DA RELAÇÃO EM HISTORIAMENTO';
-- COMENTARIOS - H_SITUACAO_COMPRA
COMMENT ON TABLE H_SITUACAO_COMPRA IS 'RELAÇÃO RESPONSÁVEL POR PERSISTIR OS TIPOS DE SITUAÇÃO DE COMPRA';
COMMENT ON COLUMN H_SITUACAO_COMPRA.HSTC_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA SITUAÇÃO DE COMPRA HISTORIADA';
COMMENT ON COLUMN H_SITUACAO_COMPRA.HSTC_STATUS IS 'STATUS DA SITUAÇÃO DE COMPRA HISTORIADA';
COMMENT ON COLUMN H_SITUACAO_COMPRA.HSTC_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DA SITUAÇÃO DE COMPRA HISTORIADA';
-- COMENTARIOS - H_TIPO_PAGAMENTO
COMMENT ON TABLE H_TIPO_PAGAMENTO IS 'RELAÇÃO RESPONSÁVEL POR PERISITSIR O HISTORIAMENTO DOS TIPOS DE PAGAMENTO DE UMA TRANSAÇÃO DE COMPRA';
COMMENT ON COLUMN H_TIPO_PAGAMENTO.HTPG_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO TIPO DE PAGAMENTO HISTORIADO';
COMMENT ON COLUMN H_TIPO_PAGAMENTO.HTPG_CATEGORIA IS 'CATEGORIA DO TIPO DE PAGAMENTO HISTORIADO';
COMMENT ON COLUMN H_TIPO_PAGAMENTO.HTPG_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO TIPO DE PAGAMENTO HISTORIADO';
-- COMENTARIOS - H_TRANSACOES_PAGAMENTO
COMMENT ON TABLE H_TRANSACOES_PAGAMENTO IS 'RELAÇÃO  RESPONSÁVEL POR PERSISTIR O HISTORIAMENTO DAS TRANSAÇÕES ASSOCIADAS A UM PAGAMENTO';
COMMENT ON COLUMN H_TRANSACOES_PAGAMENTO.HTNP_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DA TRANSAÇÃO HISTORIADA';
COMMENT ON COLUMN H_TRANSACOES_PAGAMENTO.HTNP_VALOR_PAGO IS 'VALOR PAGO NA TRANSAÇÃO HISTORIADA';
COMMENT ON COLUMN H_TRANSACOES_PAGAMENTO.HTNP_PGM_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO REFERENCIAL AO PAGAMENTO DA TRANSAÇÃO HISTORIADA';
COMMENT ON COLUMN H_TRANSACOES_PAGAMENTO.HTNP_TPG_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO REFERENCIAL AO TIPO DE PAGAMENTO ASSOCIADO A TRANSAÇÃO HISTORIADA';
COMMENT ON COLUMN H_TRANSACOES_PAGAMENTO.HTNP_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DA TRANSAÇÃO DE PAGAMENTO HISTORIADA';
-- COMENTARIOS - H_VENDEDOR
COMMENT ON TABLE H_VENDEDOR IS 'RELAÇÃO RESPONSÁVEL PELAS INFORMAÇÕES DO VENDEDOR';
COMMENT ON COLUMN H_VENDEDOR.HVDD_ID IS 'CÓDIGO IDENTIFICADOR ÚNICO DO VENDEDOR HISTORIADO';
COMMENT ON COLUMN H_VENDEDOR.HVDD_ASSINATURA IS 'ASSINATURA DO VENDEDOR HISTORIADO';
COMMENT ON COLUMN H_VENDEDOR.HVDD_CEP_ID IS 'CÓDIGO IDENTIFICADOR ESTRANGEIRO DO CEP AGREGADO AO VENDEDOR HISTORIADO';
COMMENT ON COLUMN H_VENDEDOR.HVDD_DATA_CRIACAO IS 'DATA DE CRIAÇÃO DO VENDEDOR HISTORIADO';