---------------------------------------
-- CONSTRAINTS DE HISTORIAMENTO
-- Define as constraints definidoras das entidades histórico
---------------------------------------
-- RELAÇÃO H_AVALIACAO_COMPRA
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_ID" CONSTRAINT CK_HALC_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_SCORE" CONSTRAINT CK_HALC_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_TITULO" CONSTRAINT CK_HALC_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_MENSAGEM" CONSTRAINT CK_HALC_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_DATA_HORA_CRIACAO" CONSTRAINT CK_HALC_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_CMP_ID" CONSTRAINT CK_HALC_NN_06 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
MODIFY (
        "HALC_DATA_CRIACAO" CONSTRAINT CK_HALC_NN_07 NOT NULL ENABLE
    );
ALTER TABLE H_AVALIACAO_COMPRA
ADD CONSTRAINT PK_HALC PRIMARY KEY ("HALC_ID", "HALC_DATA_CRIACAO");
-- RELAÇÃO H_CATEGORIA_PRODUTO
ALTER TABLE H_CATEGORIA_PRODUTO
MODIFY (
        "HCTP_ID" CONSTRAINT CK_HCTP_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_CATEGORIA_PRODUTO
MODIFY (
        "HCTP_NOME" CONSTRAINT CK_HCTP_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_CATEGORIA_PRODUTO
MODIFY (
        "HCTP_NOME_INGLES" CONSTRAINT CK_HCTP_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_CATEGORIA_PRODUTO
MODIFY (
        "HCTP_DATA_CRIACAO" CONSTRAINT CK_HCTP_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_CATEGORIA_PRODUTO
ADD CONSTRAINT PK_HCTP PRIMARY KEY ("HCTP_ID", "HCTP_DATA_CRIACAO");
-- RELAÇÃO H_CEP
ALTER TABLE H_CEP
MODIFY (
        "HCEP_ID" CONSTRAINT CK_HCEP_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_CEP
MODIFY (
        "HCEP_LATITUDE" CONSTRAINT CK_HCEP_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_CEP
MODIFY (
        "HCEP_LONGITUDE" CONSTRAINT CK_HCEP_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_CEP
MODIFY (
        "HCEP_CDD_ID" CONSTRAINT CK_HCEP_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_CEP
MODIFY (
        "HCEP_DATA_CRIACAO" CONSTRAINT CK_HCEP_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_CEP
ADD CONSTRAINT PK_HCEP PRIMARY KEY ("HCEP_ID", "HCEP_DATA_CRIACAO");
-- RELAÇÃO H_CIDADE
ALTER TABLE H_CIDADE
MODIFY (
        "HCDD_ID" CONSTRAINT CK_HCDD_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_CIDADE
MODIFY (
        "HCDD_NOME" CONSTRAINT CK_HCDD_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_CIDADE
MODIFY (
        "HCDD_ETD_ID" CONSTRAINT CK_HCDD_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_CIDADE
MODIFY (
        "HCDD_DATA_CRIACAO" CONSTRAINT CK_HCDD_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_CIDADE
ADD CONSTRAINT PK_HCDD PRIMARY KEY ("HCDD_ID", "HCDD_DATA_CRIACAO");
-- RELAÇÃO H_CLIENTE
ALTER TABLE H_CLIENTE
MODIFY (
        "HCLI_ID" CONSTRAINT CK_HCLI_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_CLIENTE
MODIFY (
        "HCLI_ASSINATURA" CONSTRAINT CK_HCLI_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_CLIENTE
MODIFY (
        "HCLI_CEP_ID" CONSTRAINT CK_HCLI_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_CLIENTE
MODIFY (
        "HCLI_DATA_CRIACAO" CONSTRAINT CK_HCLI_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_CLIENTE
ADD CONSTRAINT PK_HCLI PRIMARY KEY ("HCLI_ID", "HCLI_DATA_CRIACAO");
-- RELAÇÃO H_COMPRA
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_ID" CONSTRAINT CK_HCMP_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_ASSINATURA" CONSTRAINT CK_HCMP_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_DATA_COMPRA" CONSTRAINT CK_HCMP_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_ENTREGA__PREVISTA" CONSTRAINT CK_HCMP_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_VDD_ID" CONSTRAINT CK_HCMP_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_CLI_ID" CONSTRAINT CK_HCMP_NN_06 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
MODIFY (
        "HCMP_DATA_CRIACAO" CONSTRAINT CK_HCMP_NN_07 NOT NULL ENABLE
    );
ALTER TABLE H_COMPRA
ADD CONSTRAINT PK_HCMP PRIMARY KEY ("HCMP_ID", "HCMP_DATA_CRIACAO");
-- RELAÇÃO H_ESTADO
ALTER TABLE H_ESTADO
MODIFY (
        "HETD_ID" CONSTRAINT CK_HETD_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_ESTADO
MODIFY (
        "HETD_NOME" CONSTRAINT CK_HETD_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_ESTADO
MODIFY (
        "HETD_DATA_CRIACAO" CONSTRAINT CK_HETD_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_ESTADO
ADD CONSTRAINT PK_HETD PRIMARY KEY ("HETD_ID", "HETD_DATA_CRIACAO");
-- RELAÇÃO H_HISTORICO_SITUACAO_COMPRA
ALTER TABLE H_HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HHSC_ID" CONSTRAINT CK_HHSC_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HHSC_DATA_ATUALIZACAO" CONSTRAINT CK_HHSC_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HHSC_STC_ID" CONSTRAINT CK_HHSC_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HHSC_CMP_ID" CONSTRAINT CK_HHSC_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_HISTORICO_SITUACAO_COMPRA
MODIFY (
        "HHSC_DATA_CRIACAO" CONSTRAINT CK_HHSC_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_HISTORICO_SITUACAO_COMPRA
ADD CONSTRAINT PK_HHSC PRIMARY KEY ("HHSC_ID", "HHSC_DATA_CRIACAO");
-- RELAÇÃO H_ITEMS_COMPRA
ALTER TABLE H_ITEMS_COMPRA
MODIFY (
        "HITC_PRD_ID" CONSTRAINT CK_HITC_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_ITEMS_COMPRA
MODIFY (
        "HITC_CMP_ID" CONSTRAINT CK_HITC_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_ITEMS_COMPRA
MODIFY (
        "HITC_QUANTIDADE" CONSTRAINT CK_HITC_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_ITEMS_COMPRA
MODIFY (
        "HITC_ID" CONSTRAINT CK_HITC_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_ITEMS_COMPRA
MODIFY (
        "HITC_DATA_CRIACAO" CONSTRAINT CK_HITC_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_ITEMS_COMPRA
ADD CONSTRAINT PK_HITC PRIMARY KEY ("HITC_ID", "HITC_DATA_CRIACAO");
-- RELAÇÃO H_PAGAMENTO
ALTER TABLE H_PAGAMENTO
MODIFY (
        "HPGM_ID" CONSTRAINT CK_HPGM_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_PAGAMENTO
MODIFY (
        "HPGM_PARCELAS" CONSTRAINT CK_HPGM_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_PAGAMENTO
MODIFY (
        "HPGM_CMP_ID" CONSTRAINT CK_HPGM_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_PAGAMENTO
MODIFY (
        "HPGM_DATA_CRIACAO" CONSTRAINT CK_HPGM_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_PAGAMENTO
ADD CONSTRAINT PK_HPGM PRIMARY KEY ("HPGM_ID", "HPGM_DATA_CRIACAO");
-- RELAÇÃO H_PRODUTO
ALTER TABLE H_PRODUTO
MODIFY (
        "HPRD_ID" CONSTRAINT CK_HPRD_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO
MODIFY (
        "HPRD_CODIGO" CONSTRAINT CK_HPRD_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO
MODIFY (
        "HPRD_LARGURA" CONSTRAINT CK_HPRD_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO
MODIFY (
        "HPRD_PROFUNDIDADE" CONSTRAINT CK_HPRD_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO
MODIFY (
        "HPRD_PRECO" CONSTRAINT CK_HPRD_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO
MODIFY (
        "HPRD_DATA_CRIACAO" CONSTRAINT CK_HPRD_NN_06 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO
ADD CONSTRAINT PK_HPRD PRIMARY KEY ("HPRD_ID", "HPRD_DATA_CRIACAO");
-- RELAÇÃO H_PRODUTO_CATEGORIA
ALTER TABLE H_PRODUTO_CATEGORIA
MODIFY (
        "HPRC_PRD_ID" CONSTRAINT CK_HPRC_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO_CATEGORIA
MODIFY (
        "HPRC_CTP_ID" CONSTRAINT CK_HPRC_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO_CATEGORIA
MODIFY (
        "HPRC_DATA_CRIACAO" CONSTRAINT CK_HPRC_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_PRODUTO_CATEGORIA
ADD CONSTRAINT PK_HPRC PRIMARY KEY (
        "HPRC_PRD_ID",
        "HPRC_CTP_ID",
        "HPRC_DATA_CRIACAO"
    );
-- RELAÇÃO H_SITUACAO_COMPRA
ALTER TABLE H_SITUACAO_COMPRA
MODIFY (
        "HSTC_ID" CONSTRAINT CK_HSTC_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_SITUACAO_COMPRA
MODIFY (
        "HSTC_STATUS" CONSTRAINT CK_HSTC_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_SITUACAO_COMPRA
MODIFY (
        "HSTC_DATA_CRIACAO" CONSTRAINT CK_HSTC_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_SITUACAO_COMPRA
ADD CONSTRAINT PK_HSTC PRIMARY KEY ("HSTC_ID", "HSTC_DATA_CRIACAO");
-- RELAÇÃO H_TRANSACOES_PAGAMENTO
ALTER TABLE H_TRANSACOES_PAGAMENTO
MODIFY (
        "HTNP_ID" CONSTRAINT CK_HTNP_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_TRANSACOES_PAGAMENTO
MODIFY (
        "HTNP_VALOR_PAGO" CONSTRAINT CK_HTNP_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_TRANSACOES_PAGAMENTO
MODIFY (
        "HTNP_PGM_ID" CONSTRAINT CK_HTNP_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_TRANSACOES_PAGAMENTO
MODIFY (
        "HTNP_TPG_ID" CONSTRAINT CK_HTNP_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_TRANSACOES_PAGAMENTO
MODIFY (
        "HTNP_DATA_CRIACAO" CONSTRAINT CK_HTNP_NN_05 NOT NULL ENABLE
    );
ALTER TABLE H_TRANSACOES_PAGAMENTO
ADD CONSTRAINT PK_HTNP PRIMARY KEY ("HTNP_ID", "HTNP_DATA_CRIACAO");
-- RELAÇÃO H_TIPO_PAGAMENTO
ALTER TABLE H_TIPO_PAGAMENTO
MODIFY (
        "HTPG_ID" CONSTRAINT CK_HTPG_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_TIPO_PAGAMENTO
MODIFY (
        "HTPG_CATEGORIA" CONSTRAINT CK_HTPG_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_TIPO_PAGAMENTO
MODIFY (
        "HTPG_DATA_CRIACAO" CONSTRAINT CK_HTPG_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_TIPO_PAGAMENTO
ADD CONSTRAINT PK_HTPG PRIMARY KEY ("HTPG_ID", "HTPG_DATA_CRIACAO");
-- RELAÇÃO H_VENDEDOR
ALTER TABLE H_VENDEDOR
MODIFY (
        "HVDD_ID" CONSTRAINT CK_HVDD_NN_01 NOT NULL ENABLE
    );
ALTER TABLE H_VENDEDOR
MODIFY (
        "HVDD_ASSINATURA" CONSTRAINT CK_HVDD_NN_02 NOT NULL ENABLE
    );
ALTER TABLE H_VENDEDOR
MODIFY (
        "HVDD_CEP_ID" CONSTRAINT CK_HVDD_NN_03 NOT NULL ENABLE
    );
ALTER TABLE H_VENDEDOR
MODIFY (
        "HVDD_DATA_CRIACAO" CONSTRAINT CK_HVDD_NN_04 NOT NULL ENABLE
    );
ALTER TABLE H_VENDEDOR
ADD CONSTRAINT PK_HVDD PRIMARY KEY ("HVDD_ID", "HVDD_DATA_CRIACAO");