--------------------------------------------
-- SEQUENCIAS
--------------------------------------------
-- SEQUENCIA - AVALIACAO COMPRA
CREATE SEQUENCE "ALC_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - CATEGORIA PRODUTO
CREATE SEQUENCE "CTP_SEQ" MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - CEP
CREATE SEQUENCE "CEP_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - CIDADE
CREATE SEQUENCE "CDD_SEQ" MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - CLIENTE
CREATE SEQUENCE "CLI_SEQ" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - COMPRA
CREATE SEQUENCE "CMP_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - ESTADO
CREATE SEQUENCE "ETD_SEQ" MINVALUE 1 MAXVALUE 99 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - HISTORICO SITUACAO COMPRA
CREATE SEQUENCE "HSC_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - ITEMS COMPRA
CREATE SEQUENCE "ITC_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - PAGAMENTO
CREATE SEQUENCE "PGM_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - PRODUTO
CREATE SEQUENCE "PRD_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - PRODUTO CATEGORIA
CREATE SEQUENCE "PRC_SEQ" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - SITUACAO COMPRA
CREATE SEQUENCE "STC_SEQ" MINVALUE 1 MAXVALUE 99 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - TRANSACOES PAGAMENTO
CREATE SEQUENCE "TNP_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - TIPO PAGAMENTO
CREATE SEQUENCE "TPG_SEQ" MINVALUE 1 MAXVALUE 99 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
-- SEQUENCIA - VENDEDOR
CREATE SEQUENCE "VDD_SEQ" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;