---------------------------------------
-- RELAÇÕES
-- Define as entidades do minimundo
---------------------------------------
-- RELACAO CATEGORIA PRODUTO
CREATE TABLE CATEGORIA_PRODUTO (
    CTP_ID NUMBER (4),
    CTP_NOME VARCHAR2 (40 CHAR),
    CTP_NOME_INGLES VARCHAR2 (40 CHAR)
) LOGGING;
-- RELACAO CEP
CREATE TABLE CEP (
    CEP_ID NUMBER (9),
    CEP_LATITUDE NUMBER (9, 6),
    CEP_LONGITUDE NUMBER (9, 6),
    CEP_CDD_ID NUMBER (4)
) LOGGING;
-- RELACAO CIDADE
CREATE TABLE CIDADE (
    CDD_ID NUMBER (4),
    CDD_NOME VARCHAR2 (40 CHAR),
    CDD_ETD_ID NUMBER (2)
) LOGGING;
-- RELACAO ESTADO
CREATE TABLE ESTADO (
    ETD_ID NUMBER (2),
    ETD_NOME VARCHAR2 (25)
) LOGGING;
-- RELACAO TIPO PAGAMENTO
CREATE TABLE TIPO_PAGAMENTO (
    TPG_ID NUMBER (2),
    TPG_CATEGORIA VARCHAR2 (15 CHAR)
) LOGGING;
-- RELACAO VENDEDOR
CREATE TABLE VENDEDOR (
    VDD_ID NUMBER (8),
    VDD_ASSINATURA VARCHAR2 (60 CHAR)
) LOGGING;