---------------------------------------
-- RELAÇÕES
-- Define as entidades do minimundo
---------------------------------------
-- RELACAO - AVALIACAO COMPRA
CREATE TABLE AVALIACAO_COMPRA (
    ALC_ID NUMBER (10),
    ALC_SCORE NUMBER (2, 2),
    ALC_TITULO VARCHAR2 (90 CHAR),
    ALC_MENSAGEM CLOB,
    ALC_DATA_HORA_CRIACAO DATE,
    ALC_CMP_ID NUMBER (10)
) LOGGING;
-- RELACAO - CATEGORIA PRODUTO
CREATE TABLE CATEGORIA_PRODUTO (
    CTP_ID NUMBER (4),
    CTP_NOME VARCHAR2 (40 CHAR),
    CTP_NOME_INGLES VARCHAR2 (40 CHAR)
) LOGGING;
-- RELACAO - CEP
CREATE TABLE CEP (
    CEP_ID NUMBER (6),
    CEP_LATITUDE NUMBER (9, 6),
    CEP_LONGITUDE NUMBER (9, 6),
    CEP_CDD_ID NUMBER (4)
) LOGGING;
-- RELACAO - CIDADE
CREATE TABLE CIDADE (
    CDD_ID NUMBER (4),
    CDD_NOME VARCHAR2 (40 CHAR),
    CDD_ETD_ID NUMBER (2)
) LOGGING;
-- RELACAO - CLIENTE
CREATE TABLE CLIENTE (
    CLI_ID NUMBER (8),
    CLI_ASSINATURA VARCHAR2 (60 CHAR),
    CLI_CEP_ID NUMBER (6)
) LOGGING;
-- RELACAO - COMPRA
CREATE TABLE COMPRA (
    CMP_ID NUMBER (10),
    CMP_ASSINATURA VARCHAR2 (60 CHAR),
    CMP_DATA_COMPRA DATE,
    CMP_ENTREGA__PREVISTA DATE,
    CMP_VDD_ID NUMBER (8),
    CMP_CLI_ID NUMBER (8)
) LOGGING;
-- RELACAO - ESTADO
CREATE TABLE ESTADO (
    ETD_ID NUMBER (2),
    ETD_NOME VARCHAR2 (25)
) LOGGING;
-- RELACAO - HISTORICO SITUACAO COMPRA
CREATE TABLE HISTORICO_SITUACAO_COMPRA (
    HSC_ID NUMBER (10),
    HSC_DATA_ATUALIZACAO DATE,
    HSC_STC_ID NUMBER (2),
    HSC_CMP_ID NUMBER (10)
) LOGGING;
-- RELACAO - ITEMS COMPRA
CREATE TABLE ITEMS_COMPRA (
    ITC_PRD_ID NUMBER (6),
    ITC_CMP_ID NUMBER (10),
    ITC_QUANTIDADE NUMBER (6),
    ITC_ID NUMBER (10)
) LOGGING;
-- RELACAO - PAGAMENTO
CREATE TABLE PAGAMENTO (
    PGM_ID NUMBER (10),
    PGM_PARCELAS NUMBER (3),
    PGM_CMP_ID NUMBER (10)
) LOGGING;
-- RELACAO - PRODUTO
CREATE TABLE PRODUTO (
    PRD_ID NUMBER (6),
    PRD_CODIGO VARCHAR2 (100 CHAR),
    PRD_LARGURA NUMBER (4),
    PRD_PROFUNDIDADE NUMBER (5),
    PRD_PRECO NUMBER (4, 2)
) LOGGING;
-- RELACAO - PRODUTO CATEGORIA
CREATE TABLE PRODUTO_CATEGORIA (
    PRC_PRD_ID NUMBER (6),
    PRC_CTP_ID NUMBER (4)
) LOGGING;
-- RELACAO - SITUACAO COMPRA
CREATE TABLE SITUACAO_COMPRA (
    STC_ID NUMBER (2),
    STC_STATUS VARCHAR2 (15)
) LOGGING;
-- RELACAO - TRANSACOES PAGAMENTO
CREATE TABLE TRANSACOES_PAGAMENTO (
    TNP_ID NUMBER (10),
    TNP_VALOR_PAGO NUMBER (6, 2),
    TNP_PGM_ID NUMBER (10),
    TNP_TPG_ID NUMBER (2)
) LOGGING;
-- RELACAO - TIPO PAGAMENTO
CREATE TABLE TIPO_PAGAMENTO (
    TPG_ID NUMBER (2),
    TPG_CATEGORIA VARCHAR2 (15 CHAR)
) LOGGING;
-- RELACAO - VENDEDOR
CREATE TABLE VENDEDOR (
    VDD_ID NUMBER (8),
    VDD_ASSINATURA VARCHAR2 (60 CHAR),
    VDD_CEP_ID NUMBER (6)
) LOGGING;