---------------------------------------
-- RELAÇÕES
-- Define as entidades do minimundo
---------------------------------------
-- RELACAO AVALIAÇÃO COMPRA
CREATE TABLE AVALIACAO_COMPRA (
    ALC_ID NUMBER (10),
    ALC_SCORE NUMBER (2, 2),
    ALC_TITULO VARCHAR2 (90 CHAR),
    ALC_MENSAGEM CLOB,
    ALC_DATA_HORA_CRIACAO DATE,
    COMPRA_COMPRA_ID NUMBER
) LOGGING;
-- RELACAO CATEGORIA PRODUTO
CREATE TABLE CATEGORIA_PRODUTO (
    CTP_ID NUMBER (4),
    CTP_NOME VARCHAR2 (40 CHAR),
    CTP_NOME_INGLES VARCHAR2 (40 CHAR)
) LOGGING;
-- RELACAO CEP
CREATE TABLE CEP (
    CEP_ID NUMBER (6),
    CEP_LATITUDE NUMBER (9, 6),
    CEP_LONGITUDE NUMBER (9, 6),
    CIDADE_CDD_ID NUMBER (4),
    CIDADE_ETD_ID NUMBER (2),
    VENDEDOR_VDD_ID NUMBER (8),
    CLIENTE_CLI_ID NUMBER (8)
) LOGGING;
-- RELACAO CIDADE
CREATE TABLE CIDADE (
    CDD_ID NUMBER (4),
    CDD_NOME VARCHAR2 (40 CHAR),
    ESTADO_ETD_ID NUMBER (2)
) LOGGING;
-- RELACAO CLIENTE
CREATE TABLE CLIENTE (
    CLI_ID NUMBER (8),
    CLI_ASSINATURA VARCHAR2 (60 CHAR)
) LOGGING;
-- RELACAO COMPRA
CREATE TABLE COMPRA (
    CMP_ID NUMBER (10),
    CMP_ASSINATURA VARCHAR2 (60 CHAR),
    CMP_DATA_COMPRA DATE,
    CMP_ENTREGA__PREVISTA DATE,
    VENDEDOR_VDD_ID NUMBER (8),
    CLIENTE_CLI_ID NUMBER (8),
    COMPRA_ID NUMBER
) LOGGING;
-- RELACAO ESTADO
CREATE TABLE ESTADO (
    ETD_ID NUMBER (2),
    ETD_NOME VARCHAR2 (25)
) LOGGING;
-- RELACAO HISTORICO SITUAÇÃO COMPRA
CREATE TABLE HISTORICO_SITUACAO_COMPRA (
    HSC_ID NUMBER (10),
    HSC_DATA_ATUALIZACAO DATE,
    SITUACAO_COMPRA_STC_ID NUMBER (2),
    COMPRA_COMPRA_ID NUMBER
) LOGGING;
-- RELACAO ITEMS COMPRA
CREATE TABLE ITEMS_COMPRA (
    PRODUTO_PRD_ID NUMBER (6),
    COMPRA_COMPRA_ID NUMBER,
    ITC_FRETE NUMBER (4, 2),
    ITC_QUANTIDADE NUMBER (5)
) LOGGING;
-- RELACAO PAGAMENTO
CREATE TABLE PAGAMENTO (
    PGM_ID NUMBER (10),
    PGM_PARCELAS NUMBER (3),
    COMPRA_COMPRA_ID NUMBER
) LOGGING;
-- RELACAO PRODUTO
CREATE TABLE PRODUTO (
    PRD_ID NUMBER (6),
    PRD_CODIGO VARCHAR2 (100 CHAR),
    PRD_LARGURA NUMBER (4),
    PRD_PROFUNDIDADE NUMBER (5),
    PRD_PRECO NUMBER (4, 2)
) LOGGING;
-- RELACAO PRODUTO CATEGORIA
CREATE TABLE PRODUTO_CATEGORIA (
    PRODUTO_PRD_ID NUMBER (6),
    CATEGORIA_PRODUTO_CTP_ID NUMBER (4)
) LOGGING;
-- RELACAO SITUAÇÃO COMPRA
CREATE TABLE SITUACAO_COMPRA (
    STC_ID NUMBER (2),
    STC_STATUS VARCHAR2 (15)
) LOGGING;
-- RELACAO TIPO PAGAMENTO
CREATE TABLE TIPO_PAGAMENTO (
    TPG_ID NUMBER (2),
    TPG_CATEGORIA VARCHAR2 (15 CHAR)
) LOGGING;
-- RELACAO TRANSAÇÕES PAGAMENTO
CREATE TABLE TRANSACOES_PAGAMENTO (
    TNP_ID NUMBER (10),
    TNP_VALOR_PAGO NUMBER (6, 2),
    PAGAMENTO_PGM_ID NUMBER (10),
    TIPO_PAGAMENTO_TPG_ID NUMBER (2)
) LOGGING;
-- RELACAO VENDEDOR
CREATE TABLE VENDEDOR (
    VDD_ID NUMBER (8),
    VDD_ASSINATURA VARCHAR2 (60 CHAR)
) LOGGING;