-------------------------------------------
-- TRIGGERS
-------------------------------------------
-- TRIGGER - AVALIACAO COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER "ALC_TRG" BEFORE
INSERT ON "AVALIACAO_COMPRA" FOR EACH ROW BEGIN :new.ALC_ID := ALC_SEQ.nextval;
END;
/ ALTER TRIGGER "ALC_TRG" ENABLE;
-- TRIGGER - CATEGORIA PRODUTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "CTP_TRG" BEFORE
INSERT ON "CATEGORIA_PRODUTO" FOR EACH ROW BEGIN :new.CTP_ID := CTP_SEQ.nextval;
END;
/ ALTER TRIGGER "CTP_TRG" ENABLE;
-- TRIGGER - CEP
CREATE OR REPLACE NONEDITIONABLE TRIGGER "CEP_TRG" BEFORE
INSERT ON "CEP" FOR EACH ROW BEGIN :new.CEP_ID := CEP_SEQ.nextval;
END;
/ ALTER TRIGGER "CEP_TRG" ENABLE;
-- TRIGGER - CIDADE
CREATE OR REPLACE NONEDITIONABLE TRIGGER "CDD_TRG" BEFORE
INSERT ON "CIDADE" FOR EACH ROW BEGIN :new.CDD_ID := CDD_SEQ.nextval;
END;
/ ALTER TRIGGER "CDD_TRG" ENABLE;
-- TRIGGER - CLIENTE
CREATE OR REPLACE NONEDITIONABLE TRIGGER "CLI_TRG" BEFORE
INSERT ON "CLIENTE" FOR EACH ROW BEGIN :new.CLI_ID := CLI_SEQ.nextval;
END;
/ ALTER TRIGGER "CLI_TRG" ENABLE;
-- TRIGGER - COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER "CMP_TRG" BEFORE
INSERT ON "COMPRA" FOR EACH ROW BEGIN :new.CMP_ID := CMP_SEQ.nextval;
END;
/ ALTER TRIGGER "CMP_TRG" ENABLE;
-- TRIGGER - ESTADO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "ETD_TRG" BEFORE
INSERT ON "ESTADO" FOR EACH ROW BEGIN :new.ETD_ID := ETD_SEQ.nextval;
END;
/ ALTER TRIGGER "ETD_TRG" ENABLE;
-- TRIGGER - HISTORICO SITUACAO COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER "HSC_TRG" BEFORE
INSERT ON "HISTORICO_SITUACAO_COMPRA" FOR EACH ROW BEGIN :new.HSC_ID := HSC_SEQ.nextval;
END;
/ ALTER TRIGGER "HSC_TRG" ENABLE;
-- TRIGGER - ITEMS COMPRA
CREATE OR REPLACE NONEDITIONABLE TRIGGER "ITC_TRG" BEFORE
INSERT ON "ITEMS_COMPRA" FOR EACH ROW BEGIN :new.ITC_ID := ITC_SEQ.nextval;
END;
/ ALTER TRIGGER "ITC_TRG" ENABLE;
-- TRIGGER - PAGAMENTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "PGM_TRG" BEFORE
INSERT ON "PAGAMENTO" FOR EACH ROW BEGIN :new.PGM_ID := PGM_SEQ.nextval;
END;
/ ALTER TRIGGER "PGM_TRG" ENABLE;
-- TRIGGER - PRODUTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "PRD_TRG" BEFORE
INSERT ON "PRODUTO" FOR EACH ROW BEGIN :new.PRD_ID := PRD_SEQ.nextval;
END;
/ ALTER TRIGGER "PRD_TRG" ENABLE;
CREATE OR REPLACE NONEDITIONABLE TRIGGER "STC_TRG" BEFORE
INSERT ON "SITUACAO_COMPRA" FOR EACH ROW BEGIN :new.STC_ID := STC_SEQ.nextval;
END;
/ ALTER TRIGGER "STC_TRG" ENABLE;
-- TRIGGER - TRANSACOES PAGAMENTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TNP_TRG" BEFORE
INSERT ON "TRANSACOES_PAGAMENTO" FOR EACH ROW BEGIN :new.TNP_ID := TNP_SEQ.nextval;
END;
/ ALTER TRIGGER "TNP_TRG" ENABLE;
-- TRIGGER - TIPO PAGAMENTO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TPG_TRG" BEFORE
INSERT ON "TIPO_PAGAMENTO" FOR EACH ROW BEGIN :new.TPG_ID := TPG_SEQ.nextval;
END;
/ ALTER TRIGGER "TPG_TRG" ENABLE;
-- TRIGGER - VENDEDOR
CREATE OR REPLACE NONEDITIONABLE TRIGGER "VDD_TRG" BEFORE
INSERT ON "VENDEDOR" FOR EACH ROW BEGIN :new.VDD_ID := VDD_SEQ.nextval;
END;
/ ALTER TRIGGER "VDD_TRG" ENABLE;